### ISSUE TITLE
Doesn't work with my Python 3.2.3 but does with 2.7.6

### ISSUE THREAD

**Issue by tjmustard** [gingerlime/smugline#11]
I get this error when using Python 3:

Traceback (most recent call last):
  File "./smugline.py", line 52, in <module>
    from docopt import docopt
ImportError: No module named docopt

Just letting you know.

Works perfect with 2.7 so I changed the first line to #!/usr/bin/env python2.7

**Comment by gingerlime** [comment]
I didn't test it on Python 3, but based on this error it sounds like you're simply missing a library. Make sure you have all dependencies installed via `pip install -r requirements.txt`.

**Comment by tjmustard** [comment]
Yeah I did that but it still failed. Probably an incorrect environment variable.

Love the program, thank you for making my archiving process automated!

Thank you,
TJ Mustard

**Comment by gingerlime** [comment]
Glad to hear that you find smugline useful. Thanks!

Strange. I just tested it in a python 3.4 virtualenv and it seems to work ok... Not sure why it's not working for you. I will close this for now, but if you can provide more info on how to reproduce this, I'd be happy to take another look. Otherwise, I can't really say.
